on:
  push
jobs:
  build:
    name: Building the AstroLinux as ISO
    runs-on: ubuntu-latest
    steps:
      - name: Installing dependencies
        run: |
          apt install live-build
      - name: Clearing garbage made by manual building that i forgor to clean before upload
        run: |
          lb clean
          lb config
      - name: Actuall building
        run: lb build
      - name: Uploading iso
        uses: actions/upload-artifact@v3.1.2
        with:
          name: AstroLinux.iso
          path: ~/*.iso


